cmd_vel_to_mavros:
  ros__parameters:
    input_cmd_vel_topic: /cmd_vel
    debug_cmd_vel_topic: /teleop/cmd_vel_limited
    output_cmd_vel_stamped_topic: /mavros/mavros/cmd_vel
    output_cmd_vel_unstamped_topic: /mavros/mavros/cmd_vel_unstamped
    publish_rate: 15.0
    command_timeout: 0.35
    max_linear_speed: 1.0
    max_angular_speed: 0.8
    enable_reverse: true
    publish_stamped: true
    publish_unstamped: true
    body_frame_id: base_link
